describe("serviceClient",()=>{const old=process.env;beforeEach(()=>{jest.resetModules();process.env={...old,SERVICE_REQUEST_TIMEOUT_MS:"20",SERVICE_REQUEST_RETRIES:"1",SERVICE_RETRY_DELAY_MS:"1",CIRCUIT_BREAKER_FAILURE_THRESHOLD:"3",CIRCUIT_BREAKER_RESET_TIMEOUT_MS:"20"};global.fetch=jest.fn();jest.spyOn(Math,"random").mockReturnValue(0)});afterEach(()=>{jest.restoreAllMocks();process.env=old;delete global.fetch});const ok=(status=200,body={})=>({ok:status<300,status,text:jest.fn().mockResolvedValue(JSON.stringify(body))});
test("GET/parsing",async()=>{const {request}=require("../../src/utils/serviceClient");fetch.mockResolvedValueOnce(ok(200,{a:1}));const r=await request("http://x/","/a");expect(fetch).toHaveBeenCalledWith("http://x/a",expect.objectContaining({method:"GET"}));expect(r.data).toEqual({a:1})});
test("headers/body",async()=>{const {request}=require("../../src/utils/serviceClient");process.env.INTERNAL_SERVICE_TOKEN="t";fetch.mockResolvedValueOnce(ok());await request("http://x","/a",{method:"POST",headers:{"x-request-id":"r"},body:{a:1}});const o=fetch.mock.calls[0][1];expect(o.headers["x-internal-service-token"]).toBe("t");expect(o.headers["x-request-id"]).toBe("r");expect(o.body).toBe('{"a":1}')});
test("empty/invalid JSON",async()=>{const {request}=require("../../src/utils/serviceClient");fetch.mockResolvedValueOnce({ok:true,status:204,text:jest.fn().mockResolvedValue("")});expect((await request("http://x","/a")).data).toBeNull();fetch.mockResolvedValueOnce({ok:true,status:200,text:jest.fn().mockResolvedValue("bad")});expect((await request("http://y","/a")).data.message).toMatch(/Invalid JSON/)});
test("safe GET retries",async()=>{const {request}=require("../../src/utils/serviceClient");fetch.mockResolvedValueOnce(ok(503,{x:1})).mockResolvedValueOnce(ok());const r=await request("http://retry","/a",{retries:1});expect(fetch).toHaveBeenCalledTimes(2);expect(r.attempts).toBe(2)});
test("POST is not retried unless retrySafe",async()=>{const {request}=require("../../src/utils/serviceClient");fetch.mockResolvedValueOnce(ok(503));await request("http://post","/a",{method:"POST",retries:1});expect(fetch).toHaveBeenCalledTimes(1);fetch.mockResolvedValueOnce(ok(503)).mockResolvedValueOnce(ok());await request("http://post2","/a",{method:"POST",retries:1,retrySafe:true});expect(fetch).toHaveBeenCalledTimes(3)});
test("network and timeout errors",async()=>{const {request}=require("../../src/utils/serviceClient");fetch.mockRejectedValueOnce(new Error("down"));let r=await request("http://n","/a",{retries:0});expect(r.status).toBe(503);const e=new Error("timeout");e.name="AbortError";fetch.mockRejectedValueOnce(e);r=await request("http://t","/a",{retries:0});expect(r.status).toBe(504)});
test("circuit opens and reports status",async()=>{const {request,getCircuitStatus}=require("../../src/utils/serviceClient");fetch.mockResolvedValue(ok(503));await request("http://c","/a",{retries:0});await request("http://c","/a",{retries:0});await request("http://c","/a",{retries:0});expect(getCircuitStatus()["http://c"].state).toBe("OPEN");fetch.mockClear();const r=await request("http://c","/a");expect(fetch).not.toHaveBeenCalled();expect(r.data.code).toBe("CIRCUIT_OPEN")});
test("convenience methods",async()=>{const x=require("../../src/utils/serviceClient");fetch.mockResolvedValue(ok());await x.getJson("http://m","/g");await x.postJson("http://m","/p",{});await x.putJson("http://m","/u",{});await x.patchJson("http://m","/pa",{});await x.deleteJson("http://m","/d");expect(fetch.mock.calls.map(x=>x[1].method)).toEqual(["GET","POST","PUT","PATCH","DELETE"])})});
