const ORDER_STATUSES = [
  "PLACED",
  "CONFIRMED",
  "PACKED",
  "DISPATCHED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "CANCELLED",
  "RETURNED"
];

const VENDOR_NEXT_STATUS = {
  PLACED: ["CONFIRMED"],
  CONFIRMED: ["PACKED"],
  PACKED: ["DISPATCHED"],
  DISPATCHED: ["OUT_FOR_DELIVERY"],
  OUT_FOR_DELIVERY: ["DELIVERED"],
  DELIVERED: [],
  CANCELLED: [],
  RETURNED: []
};

const ISSUE_STATUSES = ["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"];
const ISSUE_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"];

module.exports = {
  ORDER_STATUSES,
  VENDOR_NEXT_STATUS,
  ISSUE_STATUSES,
  ISSUE_PRIORITIES
};
