apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopsphere-deployer
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shopsphere-deployer
  namespace: shopsphere
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shopsphere-deployer
  namespace: shopsphere
subjects:
  - kind: ServiceAccount
    name: shopsphere-deployer
    namespace: jenkins
roleRef:
  kind: Role
  name: shopsphere-deployer
  apiGroup: rbac.authorization.k8s.io